apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-engine-api
  labels:
    app: homemade-search-engine-api
spec:
  # Number of pod running with this Deployment schema
  replicas: 1
  # To link the pod running in the node to this deployment we define the matching labels
  selector:
    matchLabels:
      app: homemade-search-engine-api
  # Configuration of the pod
  template:
    metadata:
      labels:
        app: homemade-search-engine-api
    spec:
      # Configuration of the container running inside the pod (It can have multiple container runnning in one pod but not a good practice)
      containers:
        - name: search-engine-api-container
          # Image directly pull from docker hub
          image: vicop/homemade-search-engine-api:latest
          ports:
            - containerPort: 4000
          # Env variable for the container
          env:
            - name: GOOGLE_SEARCH_ENGINE_ID
              valueFrom:
                secretKeyRef:
                  # Name of secret object
                  name: app-api-secret
                  # Key of the data we want to use in the secret
                  key: engine-id
            - name: GOOGLE_SEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  # Name of secret object
                  name: app-api-secret
                  # Key of the data we want to use in the secret
                  key: api-key
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    # Using pod label to know where to forward request
    app: homemade-search-engine-api
  ports:
    - protocol: TCP
      # Service port
      port: 4000
      # Pod port
      targetPort: 4000
