name: Building application front
run-name: Checking potential code error in front-end application
on:
  # When to run this action
  pull_request:
    branches:
      - staging
      - main
# Different jobs it will have to do
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Using actions/checkout version to checkout/clone code
      - uses: actions/checkout@v3
      # Install the specified nodes version
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.1"
      - run: cd ./homemade-search-engine-app
      - run: npm install
      - run: npm run lint
